version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cibernova
    restart: unless-stopped
    ports:
      - "5432:5432" # Map PostgreSQL port to the same port on the host

volumes:
  postgres_data:
    driver: local

networks:
  cibernova:
    driver: bridge
